export const BRANDS_REPOSITORY = 'BRANDS_REPOSITORY';
export const BRANDS_SERVICE = 'BRANDS_SERVICE';

export const BRAND_MODELS_REPOSITORY = 'BRAND_MODELS_REPOSITORY';
export const BRAND_MODELS_SERVICE = 'BRAND_MODELS_SERVICE';

export const ISSUES_REPOSITORY = 'ISSUES_REPOSITORY';
export const ISSUES_SERVICE = 'ISSUES_SERVICE';
