export const BRAND_REPOSITORY = 'BRAND_REPOSITORY';
export const BRAND_SERVICE = 'BRAND_SERVICE';

export const BRAND_MODEL_REPOSITORY = 'BRAND_MODEL_REPOSITORY';
export const BRAND_MODEL_SERVICE = 'BRAND_MODEL_SERVICE';

export const ISSUE_REPOSITORY = 'ISSUE_REPOSITORY';
export const ISSUE_SERVICE = 'ISSUE_SERVICE';
