export const CUSTOMER_REPOSITORY = 'CUSTOMER_REPOSITORY';
export const CUSTOMER_SERVICE = 'CUSTOMER_SERVICE';

export const LOCALITY_REPOSITORY = 'LOCALITY_REPOSITORY';
export const LOCALITY_SERVICE = 'LOCALITY_SERVICE';
